### ISSUE TITLE
How to resize the site identity logo

### ISSUE THREAD

**Issue by shineboss** [godaddy/wp-ascension-theme#110]
Currently, my site identity logo is appearing too small, I would like to nearly double the size. Please advise. Thanks!

**Comment by EvanHerman** [comment]
@shineboss If you have a URL to your website I would be happy to take a look and see if I can provide some CSS to help change the size of the logo.

**Comment by shineboss** [comment]
Thank you very much, it's www.psfamilyservices.com.<http://www.psfamilyservices.com>


Michelle


________________________________

**Comment by EvanHerman** [comment]
The logo is tied to the height of the parent container. You can try the following:

```css
@media only screen and (min-width: 61.063em) {
   .site-header .custom-logo {
      max-height: 75px;
   }
}
```

You can add the above snippets to the _Additional CSS_ section of the customizer. To get there, you can head to the WordPress dashboard and in the left hand bar navigate to **Appearance > Customize** and then open up the _Additional CSS_ section once the customizer loads.

Let us know how that goes.

Evan
