### ISSUE TITLE
Menu header problems getting fixed

### ISSUE THREAD

**Issue by JoanMorci** [godaddy/wp-ascension-theme#70]
Hello @EvanHerman , I'm not sure how Github works or if you take this problem into consideration.

**Menu header problems getting fixed**

I have the parent theme 'Primer', and I can easily set the top menu so that when I scroll down the menu also goes down. But I do the same operation and same code in 'Ascension', and everything is left side (not center), and the **background only picks up the part of the menu, despite having 100% width**.

What is the problem? I show 2 screenshots and code.

**Primer** (Work well)

![primer-menu-fijado-bien](https://cloud.githubusercontent.com/assets/24545106/26102352/ee53b6c8-3a34-11e7-952a-c8fca3b658b5.jpg)

```
.main-navigation-container {
position: fixed;
top: 0px;
background-color: #4788d1;
z-index: 900;
}
```

**Ascension** (Work bad)

![ascension primer-child -menu-fijado-mal](https://cloud.githubusercontent.com/assets/24545106/26102372/fb96b614-3a34-11e7-8a08-03557555f03c.jpg)

```
.site-header-wrapper {
position: fixed;
background-color: #fff;
width: 100%;
z-index: 900;
}
```
With this upper code it is left shifted (without putting 'width' code does the same). Thanks to another web, discover more code* to center it, **although the color background still does not occupy the full width at 100%**.

_*: Code discovered_

```
left: 0;
right: 0;
```
**_Result:_**

![ascension primer-child -menu-fijado-mal-aunquecentrado](https://cloud.githubusercontent.com/assets/24545106/26102556/c45ea048-3a35-11e7-91b1-402d98d90542.jpg)

```
.site-header-wrapper {
	position: fixed;
        background-color: #fff;
	width: 100%;
	left: 0;
	right: 0;
        z-index: 900;
}
```

What is the problem?

**Comment by JoanMorci** [comment]
Sorry guys!

I saw it was another code earlier (Ascension). Everything **works fine except for the headline  when the menu is fixed... headline is capped!**

![ascension primer-child-menu-fijado-otrocodigo-tapa-titular](https://cloud.githubusercontent.com/assets/24545106/26155652/390159e8-3b14-11e7-911c-4d075488ca15.jpg)

```
#masthead.site-header {
  position: fixed;
  z-index: 100;
  width: 100%;
  top: 0px;
}
```

Any solution?

**Comment by EvanHerman** [comment]
Hi @JoanMorci ,

You are setting the nav menu to a fixed position, which causes the menu to overlay ontop of the header. You need to add a top margin to the header element, so that it accounts for the menu height.

To achieve what you are after in **Activation**, you may want to give the following a try:

```css
#masthead.site-header {
  position: fixed;
  z-index: 100;
  width: 100%;
  top: 0px;
}

.hero {
   margin-top: 157px;
}
```

However, this may not work across all devices, because the menu height may differ on smaller screen sizes (eg. the mobile menu height  is not equal to the height of the menu on a desktop device).

To account for mobile devices you may want to introduce a break point. Something like the following should work well:

```css
@media only screen and (max-width: 40.063em) {
   .hero {
      margin-top: 76px;
   }
}
```

Putting it all together would look like:

```css
#masthead.site-header {
  position: fixed;
  z-index: 100;
  width: 100%;
  top: 0px;
}

.hero {
   margin-top: 157px;
}

@media only screen and (max-width: 40.063em) {
   .hero {
      margin-top: 76px;
   }
}
```

Note: You may need to tweak the `margin-top` values to account for your site specifically.

I have tested the above by adding it to the customizer section 'Additional CSS', and things appear to be working well on my end.

Let us know if that helps out.

Best,
Evan
