### ISSUE TITLE
Adding different hero images to each page

### ISSUE THREAD

**Issue by markvidler84** [godaddy/wp-ascension-theme#75]
Hi,

Does anyone know how to add a different image in the hero section for each page? Currently is uses the same image for all pages. My website has a portfolio so I need to have a relevant image on each page. Here is the link - http://ab2.252.myftpupload.com

Thanks!

**Comment by EvanHerman** [comment]
Hi Mark,

You can't use the customizer to set a different image for each page. You can set it to use a random image, but not tell it what images to use specifically on what pages.

You will have to use CSS and the body classes that I provided in your previous thread to target each page individually. Or you can setup custom meta fields for those pages with an image upload field. Obviously, that is a bit beyond the scope of support here on Github, but it is certainly doable.

**Comment by markvidler84** [comment]
Hi Evan, thanks again. If I use CSS and the body classes to target each page individually do you have an example of what CSS to add? Can you add an image with CSS or would that HTML?

**Comment by EvanHerman** [comment]
Yes, you can add the image to the hero background via CSS.  Here are three examples:

Homepage:
```css
body.page-id-156 .hero {
  background: url( "http://miriadna.com/desctopwalls/images/max/Road-with-tenderness.jpg" ) 100%;
}
```

Services:
```css
body.page-id-158 .hero {
  background: url( "https://i.pinimg.com/originals/8b/9d/25/8b9d25948d696ad1f5f27f25e64bb465.jpg" ) 100%;
  background-size: contain;
}
```

Portfolio:
```css
body.page-id-160 .hero {
  background: url("http://www.centercityteam.com/wp-content/themes/CenterCityTeam/images/header-img_nw.jpg") 100%;
  background-size: cover;
}
```


Evan

**Comment by markvidler84** [comment]
Thanks, thats brilliant. I'll give it a try!

**Comment by markvidler84** [comment]
Hi Evan, I tried the CSS coding you suggested for the image in the hero. This is what it looks like http://ab2.252.myftpupload.com/gareth-payne/

Is there a way to fill the whole of the hero? Thanks again!

**Comment by markvidler84** [comment]
This is what I tried

.page-id-158 .hero .page-header h1 {
   text-align: center;
   padding: 7.6% 50px;
   background: url( "http://miriadna.com/desctopwalls/images/max/Road-with-tenderness.jpg" ) 100%;
}

**Comment by EvanHerman** [comment]
In my example I have provided 3 separate methods. You have not included the background-size parameter in your code at all. I'd recommend you try either `cover` or `contain`, as outlined in two of the three code snippets above.

That is most likely going to solve your issue.

**Comment by EvanHerman** [comment]
I would also recommend that you just remove the margin and set the hero to 100%, as you have asked in your other question.

Example:
```css
.hero {
   margin: 0;
   width: 100%;
   max-width: 100%;
}
```

Result:
![Results](https://cldup.com/gtoVPu6SF8.png)
