### ISSUE TITLE
Align name right next to logo

### ISSUE THREAD

**Issue by GodelMachine** [godaddy/wp-ascension-theme#86]
Hi team,

How do I align the institution name right next to the logo? As you can see, the organization name is spread over two lines. I would like the two lines of the organization name to appear next right to the logo.

My website is www.jaihindjuniorcollege.com 

Kindly reply at your earliest.

Thanks.

**Comment by EvanHerman** [comment]
Hi @GodelMachine 

You can give the following bit of CSS a try. You'll want to add it to the 'Additional CSS' section of the customizer, which you can get to from the dashboard by going to 'Appearance > Customize > Additional CSS'.

```css
.custom-logo-link,
.site-title,
.site-description {
   float: left;
}

.site-description {
   font-size: 30px;
}

.site-header .custom-logo {
   max-height: 80px;
   margin-right: 10px;
}
```

That should be a good starting point, but you may need to adjust some of the breakpoints for mobile devices.
